-- Instructions: Run this once in the Supabase SQL Editor in order to generate the table

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 80),
  category text not null check (char_length(trim(category)) > 0),
  body text not null check (char_length(trim(body)) > 0),
  visibility text not null check (visibility in ('public', 'private')),
  bg_color text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists notes_created_at_idx on public.notes (created_at desc);
create index if not exists notes_user_id_idx on public.notes (user_id);
create index if not exists notes_visibility_idx on public.notes (visibility);

alter table public.notes enable row level security;

create policy "Public notes are readable by everyone"
on public.notes
for select
using (visibility = 'public' or auth.uid() = user_id);

create policy "Authenticated users can insert their own notes"
on public.notes
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own notes"
on public.notes
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own notes"
on public.notes
for delete
to authenticated
using (auth.uid() = user_id);
